### ISSUE TITLE
How to configure jernl?

### ISSUE THREAD

**Issue by Kristinita** [jasongardnerlv/jernl#1]
### Summary

I can not configure jernl.
### Expected behavior

Working jernl after triggers.
### Actual behavior

jernl not functioning after triggers
### Steps to reproduce

I clone jernl in folder `jernl` in my `Package` path. I create folder `E:/Киролайна/Jernl`  and file `E:/Киролайна/Jernl`. Preferences → Settings - User → I add line:

`"jernl": "E:/Киролайна/Jernl",`

But when I call the command `jernl`, nothing happens. On the Tools it is not pressed.

![jernl in Tools](http://i.imgur.com/5MGhMYY.png)

![Command palette](http://i.imgur.com/DWPAtT2.png)

```
key evt: control+super+j
command: jernl
```

But I don't see nowhere `Quick panel`. What am I doing wrong?

Thanks.
### Environment
- Operating system and version:  
    [√] Windows 10 Education
  - [ ] Mac OS ...
  - [ ] Linux ...
- Sublime Text:
  - Build 3114

**Comment by jasongardnerlv** [comment]
Sorry for the late reply.

In the user settings, the property you should add is "jernl-dir", not "jernl".

If you still have problems, check the View->Show Console in Sublime and see if there are any errors there.

**Comment by Kristinita** [comment]
@jasongardnerlv , I am sorry, I was inattentive.
