### ISSUE TITLE
Adding actual time

### ISSUE THREAD

**Issue by ghost** [jasongardnerlv/jernl#5]
Would it be possible to add actual time (after date) ?
I tried it myself but then not even date was showing

J.

**Comment by jasongardnerlv** [comment]
I made a small change so that it will use the _datetime_ instead of just the _date_ when adding new entries.

To control the format of the date, use this setting in your Sublime user preferences:

`"jernl-date-format": "%m/%d/%Y -%I:%M:%S %p"`

I've updated the README with this info
